/**
 * AIInsightsPanel — reusable component for displaying patient health insights
 * generated by the AI document sync engine.
 *
 * Props:
 *  - patientId: string
 *  - compact: show only critical/warning (no info), for embedding in profile/doctor view
 *  - onInsightActed: optional callback when user clicks "Create Task"
 */
import React, { useEffect, useState, useCallback } from 'react';
import { useI18n } from '../i18n';
import { apiFetch } from '../lib/api';
import {
  Brain, AlertTriangle, Info, ShieldAlert,
  CheckCheck, X, Zap, ChevronDown, ChevronUp,
} from 'lucide-react';

export type HealthInsight = {
  id: string;
  insightType: string;
  title: string;
  content: string;
  severity: 'info' | 'warning' | 'critical';
  status: 'new' | 'acknowledged' | 'acted_upon' | 'dismissed';
  acknowledgedAt: string | null;
  relatedEntityType: string | null;
  relatedEntityId: string | null;
  sourceDocumentId: string | null;
  createdAt: string;
};

interface Props {
  patientId: string;
  compact?: boolean;
  onInsightActed?: (insight: HealthInsight) => void;
}

const SEVERITY_STYLES: Record<string, { border: string; bg: string; text: string; icon: React.ElementType }> = {
  critical: {
    border: 'border-[hsl(var(--destructive))]/40',
    bg: 'bg-[hsl(var(--destructive))]/8',
    text: 'text-[hsl(var(--destructive))]',
    icon: ShieldAlert,
  },
  warning: {
    border: 'border-[hsl(var(--warning))]/40',
    bg: 'bg-[hsl(var(--warning))]/8',
    text: 'text-[hsl(var(--warning))]',
    icon: AlertTriangle,
  },
  info: {
    border: 'border-[hsl(var(--primary))]/20',
    bg: 'bg-[hsl(var(--primary))]/5',
    text: 'text-[hsl(var(--primary))]',
    icon: Info,
  },
};

const INSIGHT_TYPE_LABEL: Record<string, { he: string; en: string }> = {
  diagnosis_update:    { he: 'עדכון אבחנה',       en: 'Diagnosis update' },
  medication_warning:  { he: 'אזהרת תרופה',        en: 'Medication warning' },
  lab_alert:           { he: 'ממצא מעבדה',          en: 'Lab alert' },
  vital_alert:         { he: 'מדד חריג',            en: 'Vital alert' },
  care_recommendation: { he: 'המלצת טיפול',         en: 'Care recommendation' },
  trend_detection:     { he: 'מגמה חריגה',          en: 'Trend detected' },
  referral_required:   { he: 'הפניה נדרשת',         en: 'Referral required' },
};

export default function AIInsightsPanel({ patientId, compact = false, onInsightActed }: Props) {
  const { dir, lang } = useI18n();
  const [insights, setInsights] = useState<HealthInsight[]>([]);
  const [loading, setLoading] = useState(true);
  const [collapsed, setCollapsed] = useState(false);
  const [actingId, setActingId] = useState<string | null>(null);

  const fetchInsights = useCallback(() => {
    setLoading(true);
    apiFetch<HealthInsight[]>(`/patients/${patientId}/health-insights?status=new`)
      .then((rows) => {
        const filtered = compact ? rows.filter((r) => r.severity !== 'info') : rows;
        setInsights(filtered);
      })
      .catch(() => setInsights([]))
      .finally(() => setLoading(false));
  }, [patientId, compact]);

  useEffect(() => {
    fetchInsights();
  }, [fetchInsights]);

  async function handleAction(id: string, action: 'acknowledge' | 'dismiss' | 'acted_upon') {
    setActingId(id);
    try {
      await apiFetch(`/health-insights/${id}/acknowledge`, {
        method: 'PATCH',
        body: JSON.stringify({ action }),
      });
      setInsights((prev) => prev.filter((i) => i.id !== id));
      if (action === 'acted_upon' && onInsightActed) {
        const insight = insights.find((i) => i.id === id);
        if (insight) onInsightActed(insight);
      }
    } catch {
      // ignore
    } finally {
      setActingId(null);
    }
  }

  if (loading) return null;
  if (insights.length === 0) return null;

  const criticalCount = insights.filter((i) => i.severity === 'critical').length;
  const warningCount = insights.filter((i) => i.severity === 'warning').length;

  return (
    <div className="section-card border-[hsl(var(--primary))]/20 space-y-3">
      {/* Header */}
      <button
        type="button"
        onClick={() => setCollapsed((c) => !c)}
        className={`flex items-center gap-2 w-full text-start ${dir === 'rtl' ? 'flex-row-reverse' : ''}`}
        aria-expanded={!collapsed}
        aria-label={lang === 'he' ? 'פאנל תובנות בריאות' : 'Health insights panel'}
      >
        <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${criticalCount > 0 ? 'bg-[hsl(var(--destructive))]/10' : 'bg-[hsl(var(--primary))]/10'}`}>
          <Brain className={`w-4 h-4 ${criticalCount > 0 ? 'text-[hsl(var(--destructive))]' : 'text-[hsl(var(--primary))]'}`} />
        </div>
        <div className="flex-1">
          <h3 className="section-title text-sm">{lang === 'he' ? 'תובנות בריאות — AI' : 'Health Insights — AI'}</h3>
          <p className="text-xs text-[hsl(var(--muted-foreground))]">
            {criticalCount > 0 && `${criticalCount} ${lang === 'he' ? 'קריטי' : 'critical'} · `}
            {warningCount > 0 && `${warningCount} ${lang === 'he' ? 'אזהרה' : 'warning'} · `}
            {insights.length} {lang === 'he' ? 'חדשות' : 'new'}
          </p>
        </div>
        {collapsed
          ? <ChevronDown className="w-4 h-4 text-[hsl(var(--muted-foreground))]" />
          : <ChevronUp className="w-4 h-4 text-[hsl(var(--muted-foreground))]" />
        }
      </button>

      {/* Insights list */}
      {!collapsed && (
        <ul className="space-y-2">
          {insights.map((insight) => {
            const styles = SEVERITY_STYLES[insight.severity] ?? SEVERITY_STYLES.info;
            const SeverityIcon = styles.icon;
            const typeLabel = INSIGHT_TYPE_LABEL[insight.insightType];
            const isActing = actingId === insight.id;

            return (
              <li
                key={insight.id}
                className={`rounded-xl border p-3 ${styles.border} ${styles.bg}`}
              >
                <div className={`flex items-start gap-2.5 ${dir === 'rtl' ? 'flex-row-reverse' : ''}`}>
                  <SeverityIcon className={`w-4 h-4 shrink-0 mt-0.5 ${styles.text}`} />
                  <div className="min-w-0 flex-1 space-y-1">
                    <div className={`flex items-center gap-2 flex-wrap ${dir === 'rtl' ? 'flex-row-reverse' : ''}`}>
                      <span className={`text-xs font-semibold ${styles.text}`}>
                        {typeLabel ? (lang === 'he' ? typeLabel.he : typeLabel.en) : insight.insightType}
                      </span>
                    </div>
                    <p className="text-sm font-medium text-[hsl(var(--foreground))]">{insight.title}</p>
                    <p className="text-xs text-[hsl(var(--muted-foreground))] leading-relaxed">{insight.content}</p>
                    <p className="text-xs text-[hsl(var(--muted-foreground))]">
                      {new Date(insight.createdAt).toLocaleString(lang === 'he' ? 'he-IL' : 'en', { dateStyle: 'short', timeStyle: 'short' })}
                    </p>

                    {/* Actions */}
                    <div className={`flex gap-2 pt-1 flex-wrap ${dir === 'rtl' ? 'flex-row-reverse' : ''}`}>
                      {onInsightActed && (
                        <button
                          type="button"
                          disabled={isActing}
                          onClick={() => handleAction(insight.id, 'acted_upon')}
                          className="btn-outline h-7 text-xs gap-1 px-2"
                        >
                          <Zap className="w-3 h-3" />
                          {lang === 'he' ? 'פעל עכשיו' : 'Act now'}
                        </button>
                      )}
                      <button
                        type="button"
                        disabled={isActing}
                        onClick={() => handleAction(insight.id, 'acknowledge')}
                        className="btn-ghost h-7 text-xs gap-1 px-2"
                      >
                        <CheckCheck className="w-3 h-3" />
                        {lang === 'he' ? 'קראתי' : 'Acknowledge'}
                      </button>
                      <button
                        type="button"
                        disabled={isActing}
                        onClick={() => handleAction(insight.id, 'dismiss')}
                        className="btn-ghost h-7 text-xs gap-1 px-2 text-[hsl(var(--muted-foreground))]"
                        aria-label={lang === 'he' ? 'סגור תובנה' : 'Dismiss insight'}
                      >
                        <X className="w-3 h-3" />
                        {lang === 'he' ? 'סגור' : 'Dismiss'}
                      </button>
                    </div>
                  </div>
                </div>
              </li>
            );
          })}
        </ul>
      )}
    </div>
  );
}
